### ISSUE TITLE
TinyBert  bert_config

### ISSUE THREAD

**Issue by paluss** [google-research/bert#1213]
Traceback (most recent call last):
  File "run_classifier.py", line 812, in <module>
    tf.app.run()
  File "D:\Python3.6.6\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "run_classifier.py", line 673, in main
    bert_config = bert.modeling.BertConfig.from_json_file(FLAGS.bert_config_file)
  File "..\bert\modeling.py", line 94, in from_json_file
    text = reader.read()
  File "D:\Python3.6.6\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 120, in read
    self._preread_check()
  File "D:\Python3.6.6\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "D:\Python3.6.6\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError:

**Comment by paluss** [comment]
please help me
