### ISSUE TITLE
there are errors in run run_pretraining.py

### ISSUE THREAD

**Issue by blueseven77** [google-research/bert#1249]
tensorflow==1.15
have turned tf.optimizers.Optimizer to tf.keras.optimizers.Optimizer

error information:
Traceback (most recent call last):
  File "run_pretraining.py", line 495, in <module>
    tf.app.run()
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_pretraining.py", line 466, in main
    estimator.train(input_fn=train_input_fn, max_steps=FLAGS.num_train_steps)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 3035, in tra
in
    rendezvous.raise_errors()
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\python\estimator\tpu\error_handling.py", line 136, in rai
se_errors
    six.reraise(typ, value, traceback)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 3030, in tra
in
    saving_listeners=saving_listeners)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1161, in _train_mode
l
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1195, in _train_mode
l_default
    saving_listeners)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1490, in _train_with
_estimator_spec
    log_step_count_steps=log_step_count_steps) as mon_sess:
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 584, in MonitoredT
rainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1014, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 725, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1207, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1212, in _create_s
ession
    return self._sess_creator.create_session()
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 878, in create_ses
sion
    self.tf_sess = self._session_creator.create_session()
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 647, in create_ses
sion
    init_fn=self._scaffold.init_fn)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\training\session_manager.py", line 296, in prepare_sess
ion
    sess.run(init_op, feed_dict=init_feed_dict)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Checksum does not match: stored 3189191466 vs. calculated on the restored bytes 1190294916
         [[node checkpoint_initializer_52 (defined at D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\framework
\ops.py:1748) ]]

Original stack trace for 'checkpoint_initializer_52':
  File "run_pretraining.py", line 495, in <module>
    tf.app.run()
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_pretraining.py", line 466, in main
    estimator.train(input_fn=train_input_fn, max_steps=FLAGS.num_train_steps)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 3030, in tra
in
    saving_listeners=saving_listeners)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1161, in _train_mode
l
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1191, in _train_mode
l_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 2857, in _ca
ll_model_fn
    config)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1149, in _call_model
_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 3126, in _mo
del_fn
    features, labels, is_export_mode=is_export_mode)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 1663, in cal
l_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 1994, in _ca
ll_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "run_pretraining.py", line 165, in model_fn
    tf.train.init_from_checkpoint(init_checkpoint, assignment_map)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\training\checkpoint_utils.py", line 291, in init_from_c
heckpoint
    init_from_checkpoint_fn)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py", line 1940, in merge_call

    return self._merge_call(merge_fn, args, kwargs)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py", line 1947, in _merge_cal
l
    return merge_fn(self._strategy, *args, **kwargs)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\training\checkpoint_utils.py", line 286, in <lambda>
    ckpt_dir_or_file, assignment_map)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\training\checkpoint_utils.py", line 334, in _init_from_
checkpoint
    _set_variable_or_list_initializer(var, ckpt_file, tensor_name_in_ckpt)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\training\checkpoint_utils.py", line 458, in _set_variab
le_or_list_initializer
    _set_checkpoint_initializer(variable_or_list, ckpt_file, tensor_name, "")
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\training\checkpoint_utils.py", line 412, in _set_checkp
oint_initializer
    ckpt_file, [tensor_name], [slice_spec], [base_type], name=name)[0]
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\ops\gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_he
lper
    op_def=op_def)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "D:\Program Files(x86)\ANACONDA\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by chandrawisnu** [comment]
#501
