### ISSUE TITLE
run_classifier error with CoLA dataset

### ISSUE THREAD

**Issue by jwnsu** [google-research/bert#144]
Default MRPC runs fine, change task name to CoLA, got following error with run_classifier:
Traceback (most recent call last):
  File "run_classifier.py", line 917, in <module>
    tf.app.run()
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_classifier.py", line 830, in main
    train_examples, label_list, FLAGS.max_seq_length, tokenizer, train_file)
  File "run_classifier.py", line 466, in file_based_convert_examples_to_features
    max_seq_length, tokenizer)
  File "run_classifier.py", line 432, in convert_single_example
    label_id = label_map[example.label]
KeyError: '#1 ID'

Anyone sees the error? Thx.

**Comment by monanahe** [comment]
The return of **ColaProcessor.get_labels** should match your own dataset's labels.
Also, the format of your datasets seems not meet the demand format.

**Comment by jwnsu** [comment]
CoLA is one of 4 supported datasets/tasks coming in original codes, not my own dataset.
