### ISSUE TITLE
extract featture of the trained chinese model error: Attempting to use uninitialized value bert/encoder/layer_11/output/LayerNorm/beta

### ISSUE THREAD

**Issue by world2vec** [google-research/bert#257]
```
 53     def _create_graph(self):
 54         self._add_plh()
 55         self.vocab = tkz.load_vocab(FLAGS.vocab_file)
 56         mask = tf.cast(tf.sequence_mask(self._input_seq_len_plh), tf.int32)
 57         bert_config = modeling.BertConfig.from_json_file(FLAGS.bert_config_file)
 58         self._bert_model = modeling.BertModel(config = bert_config, is_training = False, input_ids = self._input_plh, input_mask = mask,
 59                                use_one_hot_embeddings = False)
 60         self._feas = self._bert_model.get_sequence_output()
 61         self._var_init = tf.global_variables_initializer()
 62         self.init_var()
 63     def init_var(self):
 64         tvars = tf.trainable_variables()
 65         initialized_variable_names = {}
 66         (assignment_map, initialized_variable_names) = modeling.get_assignment_map_from_checkpoint(tvars, FLAGS.init_checkpoint)
 67         tf.train.init_from_checkpoint(FLAGS.init_checkpoint, assignment_map)
 68     def extract_feas(self, db):
 69         sess = tf.Session(graph = self._graph)
 70         #with sess.graph.as_default():
 71         #    saver = tf.train.Saver()
 72         #    saver.restore(sess, 'data/bert/chinese_L-12_H-768_A-12/bert_model.ckpt')
 73         feas = []
 74         for batch in db.read_epoch(batch_size = 16, ctx_size = 1, num_thr = 1):
 75             batch = self.bert_batch(batch)
 76             fea = self.run(sess, batch, self._feas)
 77             feas.extend(list(fea))
 78             break
 79         return feas
```

Above the most related part of code which will raise below error, if I enable line 70-72, the error will gone, what is the problem?

  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value bert/encoder/layer_11/output/LayerNorm/beta
	 [[{{node bert/encoder/layer_11/output/LayerNorm/beta/read}} = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](bert/encoder/layer_11/output/LayerNorm/beta)]]
	 [[{{node bert/encoder/Reshape_13/_25}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1781_bert/encoder/Reshape_13", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "extract_bert_feas.py", line 133, in <module>
    main()
  File "extract_bert_feas.py", line 128, in main
    train_feas = bert.extract_feas(train_db)
  File "extract_bert_feas.py", line 76, in extract_feas
    fea = self.run(sess, batch, self._feas)
  File "/var/opt/git/bitbucket/nlp/gcws/src/models.py", line 47, in run
    outputs = sess.run(nodes, feed)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value bert/encoder/layer_11/output/LayerNorm/beta
	 [[{{node bert/encoder/layer_11/output/LayerNorm/beta/read}} = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](bert/encoder/layer_11/output/LayerNorm/beta)]]
	 [[{{node bert/encoder/Reshape_13/_25}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1781_bert/encoder/Reshape_13", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'bert/encoder/layer_11/output/LayerNorm/beta/read', defined at:
  File "extract_bert_feas.py", line 133, in <module>
    main()
  File "extract_bert_feas.py", line 127, in main
    bert.create_graph()
  File "/var/opt/git/bitbucket/nlp/gcws/src/models.py", line 36, in create_graph
    self._create_graph()
  File "extract_bert_feas.py", line 59, in _create_graph
    use_one_hot_embeddings = False)
  File "/var/opt/git/bitbucket/nlp/gcws/src/bert/modeling.py", line 217, in __init__
    do_return_all_layers=True)
  File "/var/opt/git/bitbucket/nlp/gcws/src/bert/modeling.py", line 882, in transformer_model
    layer_output = layer_norm(layer_output + attention_output)
  File "/var/opt/git/bitbucket/nlp/gcws/src/bert/modeling.py", line 366, in layer_norm
    inputs=input_tensor, begin_norm_axis=-1, begin_params_axis=-1, scope=name)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 2299, in layer_norm
    trainable=trainable)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 350, in model_variable
    aggregation=aggregation)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 277, in variable
    aggregation=aggregation)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1484, in get_variable
    aggregation=aggregation)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1234, in get_variable
    aggregation=aggregation)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 538, in get_variable
    aggregation=aggregation)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 492, in _true_getter
    aggregation=aggregation)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 920, in _get_single_variable
    aggregation=aggregation)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 145, in __call__
    return cls._variable_call(*args, **kwargs)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 141, in _variable_call
    aggregation=aggregation)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 120, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 2441, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 147, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 1104, in __init__
    constraint=constraint)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 1266, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 81, in identity
    return gen_array_ops.identity(input, name=name)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3354, in identity
    "Identity", input=input, name=name)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/home/tom/pyenv/py3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value bert/encoder/layer_11/output/LayerNorm/beta
	 [[{{node bert/encoder/layer_11/output/LayerNorm/beta/read}} = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](bert/encoder/layer_11/output/LayerNorm/beta)]]
	 [[{{node bert/encoder/Reshape_13/_25}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1781_bert/encoder/Reshape_13", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by wykdg** [comment]
what is your tensorflow version

**Comment by amxineohp** [comment]
pip freeze|grep tensorflow
```
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
tensorflow-gpu==1.11.0
tensorflow-tensorboard==1.5.1

```

**Comment by libing125** [comment]
same problem. Did you figure it out?

**Comment by infinex** [comment]
Gotten the same output using 

`    with tf.Session() as sess:
        saver = tf.train.Saver()
        saver.restore(sess, '%s/bert_model.ckpt' % bert_dir)
`
OR
`    with tf.Session() as sess:
        bert_embedding.init_bert()
        sess.run(tf.global_variables_initializer())
`

**Comment by world2vec** [comment]
> same problem. Did you figure it out?
As I said

> if I enable line 70-72, the error will gone,
