### ISSUE TITLE
Still met key error with my data set

### ISSUE THREAD

**Issue by mice4869** [google-research/bert#344]
I keep meeting the key error with my own data set
Here is the error:
Traceback (most recent call last):
  File "D:/diabetes/run_classifier.py", line 950, in <module>
    tf.app.run()
  File "C:\Users\79093\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "D:/diabetes/run_classifier.py", line 863, in main
    train_examples, label_list, FLAGS.max_seq_length, tokenizer, train_file)
  File "D:/diabetes/run_classifier.py", line 498, in file_based_convert_examples_to_features
    max_seq_length, tokenizer)
  File "D:/diabetes/run_classifier.py", line 469, in convert_single_example
    label_id = label_map[example.label]
KeyError: '\ufeff2'

**Comment by bradfox2** [comment]
What was your solution to this, mice?
