### ISSUE TITLE
run_squad.py fails for Squad 2.0

### ISSUE THREAD

**Issue by mfeblowitz** [google-research/bert#353]
Line 834 of run_squad.py:
```
Traceback (most recent call last):
  File "run_squad.py", line 1285, in <module>
    tf.app.run()
  File "/homes/hny2/mfeb/anaconda3/envs/bert-gpu/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_squad.py", line 1276, in main
    output_nbest_file, output_null_log_odds_file)
  File "run_squad.py", line 834, in write_predictions
    feature = features[pred.feature_index]
IndexError: list index out of range
```
The failure _looks_ like  an empty/bogus prediction:
```
PrelimPrediction(feature_index=0, start_index=0, end_index=0, start_logit=0, end_logit=0)
```
Nothing obvious in the questionnaire. And the same questionnaire works fine under squad 1.1.

Also runs without error with `version_2_with_negative=True` removed.

**Comment by mfeblowitz** [comment]
UPDATE:
It appears that the problem is a blank line in the corpus file.

**Comment by mfeblowitz** [comment]
Re-opening, as this problem has recurred. 

Still trying to identify any contributions from the corpus and/or the questionnaire contents, e.g., spurious characters or uninterpretable words. 

The same content, when manually formatted into questions and corpus paragraphs, appears to work fine.

**Comment by mfeblowitz** [comment]
Sigh. OK - large, auto-generated questionnaires can be problematic. Only one empty question or one  empty paragraph context will kill squad 2.

I'll leave this open because the squad processing should detect and either skip or report cases. 

For my part, prevention of such cases is in order.

**Comment by zhiyongLiu1114** [comment]
hello, I have the same problem when using tensorflow-serving load a fine-tuned squad model, have you solve it?

**Comment by rzou15** [comment]
hello, I have the same problem when using tensorflow-serving load a fine-tuned squad model, have you solve it?

**Comment by zhiyongLiu1114** [comment]
when I set the number of questions only one, it works fine. But still have problem when the number of questions is greater than 1 and some of them have no valid predictions.  While offline predictions has no problem no matter how many questions are there. 
waiting for help
