### ISSUE TITLE
Can I run the run_classifier.py file in Windows 10?

### ISSUE THREAD

**Issue by Nutingnon** [google-research/bert#357]
Dear fellows and developers

Can bert be run in Windows 10 environment? I met an error on init_checkpoint when running the given example.

My environment: Windows 10 64bit, Python version 3.6.7 (in Anaconda), tensorflow version: 1.12.0

**Comment by artemisart** [comment]
> Can bert be run in Windows 10 environment?

Yes

> I met an error on init_checkpoint when running the given example.

Can you paste the message and stacktrace ?

**Comment by rboyes** [comment]
Was this resolved? I have seen a similar error on my windows version of BERT:

INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Error recorded from training_loop: Could not retrieve class for Options: google.protobuf.MessageOptions
INFO:tensorflow:training_loop marked as finished
WARNING:tensorflow:Reraising captured error
Traceback (most recent call last):
  File ".\run_classifier.py", line 981, in <module>
    tf.app.run()
  File "C:\programdata\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File ".\run_classifier.py", line 880, in main
    estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
  File "C:\programdata\Anaconda3\lib\site-packages\tensorflow\contrib\tpu\python\tpu\tpu_estimator.py", line 2409, in train
    rendezvous.raise_errors()
  File "C:\programdata\Anaconda3\lib\site-packages\tensorflow\contrib\tpu\python\tpu\error_handling.py", line 128, in raise_errors
    six.reraise(typ, value, traceback)
  File "C:\programdata\Anaconda3\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\programdata\Anaconda3\lib\site-packages\tensorflow\contrib\tpu\python\tpu\tpu_estimator.py", line 2403, in train
    saving_listeners=saving_listeners
  File "C:\programdata\Anaconda3\lib\site-packages\tensorflow\python\estimator\estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\programdata\Anaconda3\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\programdata\Anaconda3\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1241, in _train_model_default
    saving_listeners)
  File "C:\programdata\Anaconda3\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1468, in _train_with_estimator_spec
    log_step_count_steps=log_step_count_steps) as mon_sess:
  File "C:\programdata\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 504, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\programdata\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 921, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\programdata\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 643, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "C:\programdata\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1107, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "C:\programdata\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1112, in _create_session
    return self._sess_creator.create_session()
  File "C:\programdata\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 807, in create_session
    hook.after_create_session(self.tf_sess, self.coord)
  File "C:\programdata\Anaconda3\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py", line 559, in after_create_session
    "graph.pbtxt")
  File "C:\programdata\Anaconda3\lib\site-packages\tensorflow\python\framework\graph_io.py", line 71, in write_graph
    text_format.MessageToString(graph_def))
  File "C:\programdata\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 165, in MessageToString
    printer.PrintMessage(message)
  File "C:\programdata\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 355, in PrintMessage
    self.PrintField(field, element)
  File "C:\programdata\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 386, in PrintField
    self.PrintFieldValue(field, value)
  File "C:\programdata\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 422, in PrintFieldValue
    self._PrintMessageFieldValue(value)
  File "C:\programdata\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 407, in _PrintMessageFieldValue
    self.PrintMessage(value)
  File "C:\programdata\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 344, in PrintMessage
    if _IsMapEntry(field):
  File "C:\programdata\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 176, in _IsMapEntry

**Comment by Nutingnon** [comment]
Hi rboyes,

Yes, I solved it by using a tricky way: using Cygwin, which could allow me to use Linux command in Windows System. Hence, I can run those sample code in Cygwin environment, hope this can be helpful

Cheers

Kadima

**Comment by clayms** [comment]
The following worked for me on a windows 10 computer.

Powershell Windows version check
```
PS C:\> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      16299  0
```

* training from python

```
from subprocess import PIPE, Popen

bert_pwsh_cmd = ''' \
python run_classifier.py \
--task_name=cola \
--do_train=true \
--do_eval=true \
--data_dir="C:\\Users\\user1\\bert\\lba\\" \
--vocab_file="C:\\Users\\user1\\bert\\uncased\\uncased_L-12_H-768_A-12\\vocab.txt" \
--bert_config_file="C:\\Users\\user1\\bert\\uncased\\uncased_L-12_H-768_A-12\\bert_config.json" \
--init_checkpoint="C:\\Users\\user1\\bert\\uncased\\uncased_L-12_H-768_A-12\\bert_model.ckpt" \
--max_seq_length=128 \
--train_batch_size=32 \
--learning_rate=2e-5 \
--num_train_epochs=3.0 \
--output_dir="C:\\Users\\user1\\bert\\bert_output\\" \
'''

process = Popen(['powershell', bert_pwsh_cmd], stdout=PIPE, stderr=PIPE)
stdout, stderr = process.communicate()
print(stdout.decode(), stderr.decode())
```

* predicting from python

```
bert_test_pwsh_cmd = """\
python run_classifier.py \
--task_name=cola \
--do_predict=true \
--data_dir="C:\\Users\\user1\\bert\\lba\\" \
--vocab_file="C:\\Users\\user1\\bert\\uncased\\uncased_L-12_H-768_A-12\\vocab.txt" \
--bert_config_file="C:\\Users\\user1\\bert\\uncased\\uncased_L-12_H-768_A-12\\bert_config.json" \
--init_checkpoint="C:\\Users\\user1\\bert\\bert_output\\model.ckpt-2000" \
--max_seq_length=128 \
--output_dir="C:\\Users\\user1\\bert\\bert_output\\" \
"""

process = Popen(['powershell', bert_test_pwsh_cmd], stdout=PIPE, stderr=PIPE)
stdout, stderr = process.communicate()
print(stdout.decode(), stderr.decode())
```

**Comment by NancyLele** [comment]
@clayms 
thanks for you share. I have a question.The below codes  can run on pycharm?
from subprocess import PIPE, Popen

bert_pwsh_cmd = ''' \
python run_classifier.py \
--task_name=cola \
--do_train=true \
--do_eval=true \
--data_dir="C:\\Users\\user1\\bert\\lba\\" \
--vocab_file="C:\\Users\\user1\\bert\\uncased\\uncased_L-12_H-768_A-12\\vocab.txt" \
--bert_config_file="C:\\Users\\user1\\bert\\uncased\\uncased_L-12_H-768_A-12\\bert_config.json" \
--init_checkpoint="C:\\Users\\user1\\bert\\uncased\\uncased_L-12_H-768_A-12\\bert_model.ckpt" \
--max_seq_length=128 \
--train_batch_size=32 \
--learning_rate=2e-5 \
--num_train_epochs=3.0 \
--output_dir="C:\\Users\\user1\\bert\\bert_output\\" \
'''

process = Popen(['powershell', bert_pwsh_cmd], stdout=PIPE, stderr=PIPE)
stdout, stderr = process.communicate()
print(stdout.decode(), stderr.decode())

**Comment by clayms** [comment]
If you are running PyCharm on a Windows computer with Powershell installed, then it should.  Since you are calling a `subprocess`, which runs a process on the host machines shell, Pycharm (or any IDE) has nothing to do with the process.  

You can validate this by copying the output of `print(bert_pwsh_cmd)`, opening up Powershell and pasting the entire `bert_pwsh_cmd` at the Powershell prompt and running directly.

**Comment by sunlanchang** [comment]
>  [System.Environment]::OSVersion.Version

ewq
