### ISSUE TITLE
BERT SQuAD 2 fails on challenging(?) questions

### ISSUE THREAD

**Issue by mfeblowitz** [google-research/bert#417]
Traceback:
```
Traceback (most recent call last):
  File "run_squad.py", line 1286, in <module>
    tf.app.run()
  File "/home/.../site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_squad.py", line 1279, in main
    output_nbest_file, output_null_log_odds_file)
  File "run_squad.py", line 909, in write_predictions
    score_diff = score_null - best_non_null_entry.start_logit - (
AttributeError: 'NoneType' object has no attribute 'start_logit'
```
Error occurs with null `best_non_null_entry` at line 906 in `write_predictions`.
Debugging is a challenge, but inserting this at 906 helps:
```
      if  not best_non_null_entry:
        print("bad null entry for best_non_null_entry for example: %s: %s" % (example_index, example))
        exit
```
This reveals that the culprit is this question:
```
What does stagnation in real earnings for the bulk of the world's population, the middle class, particularly in western society lead to?
```
In some runs removing the apostrophe from `world's` fixed the problem. 
In other runs - with slightly different question wording around the core `stagnation in real earnings for the bulk of the world's population, the middle class, particularly in western society` - the sentence needed to be simplified to make the problem go away. Specifically, removing the comma-offset clauses: `, the middle class, particularly in western society`
 
So, one issue is to trap that null value error and provide some additional context for the error. 
The other is to determine how the null entry gets into the examples list and to prevent it.

**Comment by anshoomehra** [comment]
@mfeblowitz Thanks for reporting and debugging this. I am running into the same issue, I am just curious why only few of us running into this issue and based on the age of this issue report there is no movement at all on this - perhaps make it even rare occurrence??

How did you resolve it, am sorry am bit unclear - did you remove this example or fixed the code to get around it?

Appreciate the response.
Anshoo

**Comment by mfeblowitz** [comment]
I was only able to make it go away by purging the apostrophes and/or the commas from the text.

**Comment by mfeblowitz** [comment]
OK - so it appears that there might be multiple reasons why this failure comes up: complex sentences, unhandled special characters in  the text (including embedded apostrophes or commas, ...

It does appear that some exception happens, and rather than moving on to the next question, the processing  stops. I'm thinking that some additional exception processing can be inserted, and that there should be a flag that indicates that the errant question should be reported *_and_* skipped.

I have switched to a different approach whereby I ask each question in a separate call to bert, rather than bundling them up into one (huge) questionnaire, and then catching the exceptions and moving to the next. Also, capturing the sentence and the exception in the log, I'll be able to follow thus up with characterizations of what leads to this failure.

**Comment by mfeblowitz** [comment]
Edits to the original problem statement were made after the comments above.

**Comment by mfeblowitz** [comment]
Questions to @Anton-Velikodnyy RE #477: 
Does this this fix address the situation above, or merely prevent a mid-processing crash? The latter is good, the former would also be good.

**Comment by zjjhuihui** [comment]
I tried two ways to solve the problem, but failed,I wonder why.
**Methods a:**
`    if FLAGS.version_2_with_negative:
      if "" not in seen_predictions:
        nbest.append(
            _NbestPrediction(
                text="", start_logit=null_start_logit,
                end_logit=null_end_logit))
     
        #In very rare edge cases we could only have single null prediction.
        #So we just create a nonce prediction in this case to avoid failure.
best_non_null_entry.end_logit)scores_diff_json[example.qas_id] = score_diff的错误：AttributeError: 'NoneType' object has no attribute 'start_logit'
        if len(nbest)==1:
            nbest.insert(0,
                _NbestPrediction(text='empty',start_logit=0.0,end_logit=0.0))
       
    # In very rare edge cases we could have no valid predictions. So we
    # just create a nonce prediction in this case to avoid failure.
     
    if not nbest:`
**Methods b:**
      scores_diff_json[example.qas_id] = score_diff
 
      if best_non_null_entry:
        score_diff = score_null - best_non_null_entry.start_logit - (best_non_null_entry.end_logit)
        scores_diff_json[example.qas_id] = score_diff
      else:
        #all n best entries are null,we assign a higher diff than threshold
        score_diff = FLAGS.null_score_diff_threshold + 1.0

      if score_diff > FLAGS.null_score_diff_threshold:
        all_predictions[example.qas_id] = ""

**Comment by mfeblowitz** [comment]
I'm thinking that the lack of nbest is not due to the rare case where there are no nbests, but instead due to some characteristic of the questions and/or answers. E.g., the presence of non-printing or non-processable individual characters (e.g., bullet characters or non-breaking space characters). Or perhaps some collection of non-word characters, such as acronyms. 

I have been able to process using squad 2.0 questions that have been manually simplified questions and documents, removing some of the apparently offending characters or patterns. I'm not yet sure which of the mods were the ones that trigger the failure. But there seems to be some anomaly in to squad 2 processing that triggers a problem upstream of the nbest computation that is not seen until nbest computation is performed.

The one constant is that the upstream processing somehow generates an empty feature set, for questions and documents that - when manually cleansed - produce a rich set of answers for the questions.

I'm trying the patches in #477 and #720 to prevent any further (tedious) search for the offending patterns.

**Comment by alphamaviwiki** [comment]
I faced the same problem. I just check if anyone can fix this error. I make a try-catch command on that error but I don't know the performance will be affected or not.

    # predict "" iff the null score - the score of best non-null > threshold
      try:
        score_diff = score_null - best_non_null_entry.start_logit - (best_non_null_entry.end_logit)
      except:
        score_diff = score_null
        
      scores_diff_json[example.qas_id] = score_diff
      if score_diff > FLAGS.null_score_diff_threshold:
        all_predictions[example.qas_id] = ""
      else:
        all_predictions[example.qas_id] = best_non_null_entry.text

**Comment by lackhole** [comment]
Having same issue in 2022.
Used extra try-catch near line 906 to run it, but don't know whether it affects the result or not

```
# predict "" iff the null score - the score of best non-null > threshold
try:
  score_diff = score_null - best_non_null_entry.start_logit - (best_non_null_entry.end_logit)
except:
  score_diff = score_null

scores_diff_json[example.qas_id] = score_diff
if score_diff > FLAGS.null_score_diff_threshold:
  all_predictions[example.qas_id] = ""
else:
  try:
    all_predictions[example.qas_id] = best_non_null_entry.text
  except:
    all_predictions[example.qas_id] = ""
```

**Comment by IntelOSt** [comment]
Check region networkDian Jaka WidiawanOn Feb 8, 2022 2:26 PM, Lee Yong Gyu ***@***.***> wrote:
Having same issue in 2022

**Comment by IntelOSt** [comment]
kill fisch biden american presidentDian Jaka WidiawanOn Feb 8, 2022 6:22 PM, Steven Ian Denis ***@***.***> wrote:

Check region networkDian Jaka WidiawanOn Feb 8, 2022 2:26 PM, Lee Yong Gyu ***@***.***> wrote:



Having same issue in 2022
