### ISSUE TITLE
module 'tensorflow.python.platform.flags' has no attribute 'mark_flag_as_required'

### ISSUE THREAD

**Issue by WilliamTambellini** [google-research/bert#455]
when running the run_squad.py train example from the 'doc' (main .md file): 
 
Traceback (most recent call last):
  File "../run_squad.py", line 1280, in <module>
    flags.mark_flag_as_required("vocab_file")
AttributeError: module 'tensorflow.python.platform.flags' has no attribute 'mark_flag_as_required'

Ubuntu 16
Python 3.5
TF 0.12.0rc0

I ve searched fro root cause but did nt find one : found that : 
https://github.com/tensorflow/models/issues/2777

Requirement already satisfied: tensorflow-gpu in /usr/local/lib/python3.5/dist-packages (0.12.0rc0)
Requirement already satisfied: numpy>=1.11.0 in /usr/local/lib/python3.5/dist-packages (from tensorflow-gpu) (1.11.2)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3/dist-packages (from tensorflow-gpu) (1.10.0)
Requirement already satisfied: protobuf==3.1.0 in /usr/local/lib/python3.5/dist-packages (from tensorflow-gpu) (3.1.0)
Requirement already satisfied: wheel>=0.26 in /usr/lib/python3/dist-packages (from tensorflow-gpu) (0.29.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.5/dist-packages (from protobuf==3.1.0->tensorflow-gpu) (30.3.0)

**Comment by WilliamTambellini** [comment]
Uninstalled and reinstalled tensorflow-gpu seems to fix that.
Closing.

**Comment by sehargul-123** [comment]
Traceback (most recent call last):
File "DeepSpeech.py", line 11, in
import absl.app
File "/home/sehar/venv/lib/python3.6/site-packages/absl/app.py", line 40, in
from absl import flags
File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/init.py", line 41, in
from absl.flags import _defines
File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_defines.py", line 31, in
from absl.flags import _flagvalues
File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 27, in
import logging
File "/home/sehar/DeepSpeech/logging.py", line 6, in
from util.flags import FLAGS
File "/home/sehar/DeepSpeech/util/flags.py", line 6, in
FLAGS = absl.flags.FLAGS
AttributeError: module 'absl' has no attribute 'flags'
kindly help me to slove this error
