### ISSUE TITLE
IndexError in run_classifier.py::MrpcProcessor::_create_examples

### ISSUE THREAD

**Issue by alter-bug-tracer** [google-research/bert#550]
**What**: "IndexError: list index out of range"

**Location**: MrpcProcessor::_create_examples function from run_classifier.py

**Reason**: Missing input validation when reading the lines: wrong assumption that the list "line" has at least 5 items ('line[4]').

**Steps to reproduce**:
Corrupt the "glue_data/MRPC/train.tsv" by removing the second string (see attached example).
Run 
python run_classifier.py \\
  --task_name=MRPC \\
  --do_train=true \\
  --do_eval=true \\
  --data_dir=$GLUE_DIR/MRPC \\
  --vocab_file=$BERT_BASE_DIR/vocab.txt \\
  --bert_config_file=$BERT_BASE_DIR/bert_config.json \\
  --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt \\
  --max_seq_length=128 \\
  --train_batch_size=32 \\
  --learning_rate=2e-5 \\
  --num_train_epochs=3.0 \\
  --output_dir=/tmp/mrpc_output/

**Traceback**:
Traceback (most recent call last):
  File "bert/run_classifier.py", line 981, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "bert/run_classifier.py", line 842, in main
    train_examples = processor.get_train_examples(FLAGS.data_dir)
  File "bert/run_classifier.py", line 302, in get_train_examples
    self._read_tsv(os.path.join(data_dir, "train.tsv")), "train")
  File "bert/run_classifier.py", line 326, in _create_examples
    text_b = tokenization.convert_to_unicode(line[4])
IndexError: list index out of range

**Comment by armadillowithsunglasses** [comment]
Hi, were you able to solve this error ? I am using a custom dataset and getting the same error
