### ISSUE TITLE
$BERT_DIR\bert_config.json could not be found

### ISSUE THREAD

**Issue by JeevaTM** [google-research/bert#701]
OS: Windows 2012 R2
Python: 3.7.3

I tried to run run_squad.py using Cloud TPU. I have all the files in compute engine - Windows VM (SQUAD 2.0, Bert-master, BERT_Large_cased).

Note: I tried to set the environment variables for SQUAD and BERT_large_cased and the files where in Google storage bucket. Example: `set $SQUAD_DIR=gs://test/squad_dir`, it  throws an error saying cannot access file. All though I gave the VM service account both view and write object role for the bucket.

I set the environment variables for squad directory and bert_large_cased and tried to run using the code provided in the home page of bert in github.

Here's the code:
```
C:\Users\Desktop\bert-master>python run_squad.py \ --vocab_file=$BERT
_LARGE_DIR/vocab.txt \ --bert_config_file=$BERT_LARGE_DIR/bert_config.json \ ini
t_checkpoint=$BERT_LARGE_DIR/bert_model.ckpt \ --do_train=True \ --train_file=$S
QUAD_DIR/train-v2.0.json \ --do_predict=True \ --predict_file=$SQUAD_DIR/dev-v2.
0.json \ --train_batch_size=24 \ --learning_rate=3e-5 \ --num_train_epochs=2.0 \
 --max_seq_length=384 \ --doc_stride=128 \ --output_dir=gs://uniquetestbucket/sq
uad_large/ \ --use_tpu=True \ --tpu_name=$TPU_NAME \ --version_2_with_negative=T
rue
Traceback (most recent call last):
  File "run_squad.py", line 1283, in <module>
    tf.app.run()
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-pack
ages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_squad.py", line 1129, in main
    bert_config = modeling.BertConfig.from_json_file(FLAGS.bert_config_file)
  File "C:\Users\Desktop\bert-master\modeling.py", line 94, in from_j
son_file
    text = reader.read()
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-pack
ages\tensorflow\python\lib\io\file_io.py", line 125, in read
    self._preread_check()
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-pack
ages\tensorflow\python\lib\io\file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-pack
ages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile faile
d to Create/Open: $BERT_LARGE_DIR/bert_config.json : The system cannot find the
path specified.
; No such process
```

**Comment by JeevaTM** [comment]
Redownloading the files helped.

**Comment by Umang9427** [comment]
https://storage.googleapis.com/bert_models/2018_10_18/cased_L-12_H-768_A-12.zip link to a application specific bert-config
