### ISSUE TITLE
ValueError: For training, each question should have exactly 1 answer.

### ISSUE THREAD

**Issue by JeevaTM** [google-research/bert#702]
I tried

> Try with argument "--version_2_with_negative True"

I tried this argument. I still have the issue. 

```
python run_squad.py --vocab_file=$BERT_LARGE_DIR/vocab.txt --bert_config_file=$BERT_LARGE_DIR/bert_config.json --init_checkpoint=$BERT_LAR
GE_DIR/bert_model.ckpt --do_train=True --train_file=$SQUAD_DIR/train-v2.0.json --do_predict=True --predict_file=$SQUAD_DIR/dev-v2.0.json --train_batch_size=24 --learning_rate=
3e-5 --num_train_epochs=2.0 --max_seq_length=384 --doc_stride=128 --output_dir=gs://example/neural-output --use_tpu=True \ --tpu_name=$TPU_NAME \ --version_2_with_neg
ative True
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.
Traceback (most recent call last):
  File "run_squad.py", line 1283, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_squad.py", line 1159, in main
    input_file=FLAGS.train_file, is_training=True)
  File "run_squad.py", line 268, in read_squad_examples
    "For training, each question should have exactly 1 answer.")
ValueError: For training, each question should have exactly 1 answer.
```

and

```
python run_squad.py --vocab_file=$BERT_LARGE_DIR/vocab.txt --bert_config_file=$BERT_LARGE_DIR/bert_config.json --init_checkpoint=$BERT_LAR
GE_DIR/bert_model.ckpt --do_train=True --train_file=$SQUAD_DIR/train-v2.0.json --do_predict=True --predict_file=$SQUAD_DIR/dev-v2.0.json --train_batch_size=24 --learning_rate=
3e-5 --num_train_epochs=2.0 --max_seq_length=384 --doc_stride=128 --output_dir=gs://example/neural-output --use_tpu=True \ --tpu_name=$TPU_NAME \ --version_2_with_neg
ative=True
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.
Traceback (most recent call last):
  File "run_squad.py", line 1283, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_squad.py", line 1159, in main
    input_file=FLAGS.train_file, is_training=True)
  File "run_squad.py", line 268, in read_squad_examples
    "For training, each question should have exactly 1 answer.")
ValueError: For training, each question should have exactly 1 answer.
```

_Originally posted by @JeevaTM in https://github.com/google-research/bert/issues/392#issuecomment-503063565_

**Comment by JeevaTM** [comment]
Resolved.
Apparently `set` command in command line is completely different from `export` in bash.
I was also using local files instead of using it from Google cloud storage bucket.
I created a new VM with debian, connected to tpu (Created using `ctpu` tool). Ran the code as specified in the home page. It was successful.

F1 score: 81.375

**Comment by khaerulumam42** [comment]
This is because your training dataset have more than a question-answer pair, so for simplicity you can solve this by uncomment 266-268 to avoid that warning. Is still okay because on line 270 we just take 0 index of question-answer.
It is solved for me.

Hope it helps!
