### ISSUE TITLE
Couldn't train BERT with SQUAD 1.1

### ISSUE THREAD

**Issue by JeevaTM** [google-research/bert#706]
I created VM (n1-standard-2) and Cloud TPU (v3-8) using ctpu tool.

I have created a Storage bucket and mounted it in VM using GCSfuse.

Tried to run it. Failed.

```
python run_squad.py \
> --vocab_file=$BERT_BASE_DIR/vocab.txt \
> --bert_config_file=$BERT_BASE_DIR/bert_config.json \
> --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt \
> --do_train=True \
> --train_file=$SQUAD_DIR/train-v1.1.json \
> --do_predict=True \
> --predict_file=$SQUAD_DIR/dev-v1.1.json \
> --train_batch_size=12 \
> --learning_rate=3e-5 \
> --num_train_epochs=2.0 \
> --max_seq_length=384 \
> --doc_stride=128 \
> output_dir=$output
Traceback (most recent call last):
  File "run_squad.py", line 1283, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", l
ine 119, in run
    argv = flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/flags.py",
 line 112, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 636,
 in __call__
    self._assert_all_validators()
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 510,
 in _assert_all_validators
    self._assert_validators(all_validators)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 531,
 in _assert_validators
    raise _exceptions.IllegalFlagValueError('%s: %s' % (message, str(e)))
absl.flags._exceptions.IllegalFlagValueError: flag --output_dir=None: Flag --output_
dir must have a value other than None.
```

`$output` is `/output: Is a directory`.

**Comment by JeevaTM** [comment]
I also manually typed instead of exporting $output. Same error: --output_dir=None

**Comment by JeevaTM** [comment]
I tried to load files from local storage and not cloud storage bucket. That is why this error.

**Comment by musicfish1973** [comment]
I also encountered this problem, "--ouput_dir=/root/bert-master/squad_base/" is a local directory, so how to solve this error? Thanks a lot.

**Comment by musicfish1973** [comment]
In fact, I made a careless mistake,   "--ouput_dir" should be "--output_dir" ！
