### ISSUE TITLE
Errors with pre-training in BERT

### ISSUE THREAD

**Issue by RyanBe123** [google-research/bert#757]
I am using python 3.7 on windows 10.
I am trying to train my model using pre-trained BERT model for an NLP system I am attempting to make (following https://appliedmachinelearning.blog/2019/03/04/state-of-the-art-text-classification-using-bert-model-predict-the-happiness-hackerearth-challenge/ instructions). When I enter python run_classifier.py on the command prompt I get the following errors:

WARNING: Logging before flag parsing goes to stderr.
W0711 10:33:50.740351 16080 deprecation_wrapper.py:119] From C:\Users\ryanb\Documents\Analytics Intelligence\NLP\pre-training models\bert-master\optimization.py:87: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0711 10:33:50.745385 16080 deprecation_wrapper.py:119] From run_classifier.py:981: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

Traceback (most recent call last):
  File "C:\Users\ryanb\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\flags\_flagvalues.py", line 528, in _assert_validators
    validator.verify(self)
  File "C:\Users\ryanb\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\flags\_validators.py", line 82, in verify
    raise _exceptions.ValidationError(self.message)
absl.flags._exceptions.ValidationError: Flag --data_dir must have a value other than None.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_classifier.py", line 981, in <module>
    tf.app.run()
  File "C:\Users\ryanb\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\ryanb\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 294, in run
    flags_parser,
  File "C:\Users\ryanb\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 351, in _run_init
    flags_parser=flags_parser,
  File "C:\Users\ryanb\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 213, in _register_and_parse_flags_with_usage
    args_to_main = flags_parser(original_argv)
  File "C:\Users\ryanb\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\platform\app.py", line 31, in _parse_flags_tolerate_undef
    return flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "C:\Users\ryanb\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\platform\flags.py", line 112, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
  File "C:\Users\ryanb\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\flags\_flagvalues.py", line 636, in __call__
    self._assert_all_validators()
  File "C:\Users\ryanb\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\flags\_flagvalues.py", line 510, in _assert_all_validators
    self._assert_validators(all_validators)
  File "C:\Users\ryanb\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\flags\_flagvalues.py", line 531, in _assert_validators
    raise _exceptions.IllegalFlagValueError('%s: %s' % (message, str(e)))
absl.flags._exceptions.IllegalFlagValueError: flag --data_dir=None: Flag --data_dir must have a value other than None.

I then run it on python to see if I could get some more insight into any errors and the following came up:
DuplicateFlagError: The flag 'data_dir' is defined twice. First from C:/Users/ryanb/Documents/Analytics Intelligence/NLP/pre-training models/bert-master/run_classifier.py, Second from C:/Users/ryanb/Documents/Analytics Intelligence/NLP/pre-training models/bert-master/run_classifier2.py.  Description from first occurrence: The input data dir. Should contain the .tsv files (or other data files) for the task.

Any idea what I need to do to fix it?
Thanks in advance

**Comment by namedmo** [comment]
Have you solved it? I have the same problem
