### ISSUE TITLE
I get error when I run classifier in task MRPC 

### ISSUE THREAD

**Issue by quincyliang** [google-research/bert#81]
I pulled the latest code and run classifier with the following script
python run_classifier.py \
  --task_name=MRPC \
  --do_train=true \
  --do_eval=true \
  --do_predict=true \
  --data_dir=$GLUE_DIR/MRPC \
  --vocab_file=$BERT_BASE_DIR/vocab.txt \
  --bert_config_file=$BERT_BASE_DIR/bert_config.json \
  --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt \
  --max_seq_length=128 \
  --train_batch_size=32 \
  --learning_rate=2e-5 \
  --num_train_epochs=3.0 \
  --output_dir=$GLUE_DIR/mrpc_output/

The error message is:

INFO:tensorflow:label: 1 (id = 1)
Traceback (most recent call last):
  File "run_classifier.py", line 895, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_classifier.py", line 862, in main
    FLAGS.max_seq_length, tokenizer, predict_file)
  File "run_classifier.py", line 447, in file_based_convert_examples_to_features
    max_seq_length, tokenizer)
  File "run_classifier.py", line 417, in convert_single_example
    label_id = label_map[example.label]
KeyError: '2'

**Comment by quincyliang** [comment]
I just pulled the code again, it works for me. Thanks!
