### ISSUE TITLE
run run_classifier.py UnicodeDecodeError

### ISSUE THREAD

**Issue by xxllp** [google-research/bert#903]
Traceback (most recent call last):
  File "run_classifier.py", line 24, in <module>
  File "/home/mlp/xxl/nlp_bert/bert_ner/bert_ner/modeling.py", line 27, in <module>
    import tensorflow as tf
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 55, in <module>
    'tensorflow_estimator.python.estimator'))
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/tensorflow/python/tools/component_api_helper.py", line 56, in package_hook
    child_pkg = importlib.import_module(child_package_str)
  File "/home/mlp/python/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 8, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/__init__.py", line 25, in <module>
    import tensorflow_estimator.python.estimator.estimator_lib
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator_lib.py", line 22, in <module>
    from tensorflow_estimator.python.estimator.canned.baseline import BaselineClassifier
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/baseline.py", line 54, in <module>
    from tensorflow.python.feature_column import feature_column as feature_column_lib
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column.py", line 143, in <module>
    from tensorflow.python.keras.engine import training
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/__init__.py", line 24, in <module>
    from tensorflow.python.keras import activations
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/activations.py", line 23, in <module>
    from tensorflow.python.keras import backend as K
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 33, in <module>
    from tensorflow.python.client import session as session_module
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 36, in <module>
    from tensorflow.python.ops import session_ops
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/session_ops.py", line 34, in <module>
    from tensorflow.python.ops import array_ops
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2141, in <module>
    @ops.RegisterGradient("FakeQuantWithMinMaxArgs")
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2412, in __call__
    _gradient_registry.register(f, self._op_type)
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/registry.py", line 67, in register
    stack = traceback.extract_stack()
  File "/home/mlp/python/anaconda3/lib/python3.6/traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/home/mlp/python/anaconda3/lib/python3.6/traceback.py", line 364, in extract
    f.line
  File "/home/mlp/python/anaconda3/lib/python3.6/traceback.py", line 286, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/home/mlp/python/anaconda3/lib/python3.6/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/home/mlp/python/anaconda3/lib/python3.6/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/home/mlp/python/anaconda3/lib/python3.6/linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "/home/mlp/python/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 1338: invalid continuation byte

**Comment by xxllp** [comment]
use tensorflow-gpu 1.12
