### ISSUE TITLE
python run_classifier.py  InvalidArgumentError (see above for traceback): Found Inf or NaN global norm. : Tensor had NaN values 	 [[{{node VerifyFinite/CheckNumerics}} = CheckNumerics[T=DT_FLOAT, message="Found Inf or NaN global norm.", _device="/job:localhost/replica:0/task:0/device:GPU:0"](global_norm/global_norm)]]

### ISSUE THREAD

**Issue by zkl99999** [google-research/bert#92]
2018-11-09 17:25:36.526218: W tensorflow/core/framework/allocator.cc:113] Allocation of 93763584 exceeds 10% of system memory.
2018-11-09 17:25:36.763905: W tensorflow/core/framework/allocator.cc:113] Allocation of 93763584 exceeds 10% of system memory.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into ./tmp/model.ckpt.
2018-11-09 17:26:18.367779: E tensorflow/core/kernels/check_numerics_op.cc:185] abnormal_detected_host @0x2049ee800 = {1, 0} Found Inf or NaN global norm.
INFO:tensorflow:Error recorded from training_loop: Found Inf or NaN global norm. : Tensor had NaN values
	 [[{{node VerifyFinite/CheckNumerics}} = CheckNumerics[T=DT_FLOAT, message="Found Inf or NaN global norm.", _device="/job:localhost/replica:0/task:0/device:GPU:0"](global_norm/global_norm)]]

Caused by op 'VerifyFinite/CheckNumerics', defined at:
  File "run_classifier.py", line 910, in <module>
    tf.app.run()
  File "/home/anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_classifier.py", line 836, in main
    estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
  File "/home//anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2394, in train
    saving_listeners=saving_listeners
  File "/home//anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 356, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1181, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1211, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2186, in _call_model_fn
    features, labels, mode, config)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1169, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2470, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1250, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1524, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "run_classifier.py", line 636, in model_fn
    total_loss, learning_rate, num_train_steps, num_warmup_steps, use_tpu)
  File "/home///zklcode/pynlp/bert/bert/optimization.py", line 74, in create_optimizer
    (grads, _) = tf.clip_by_global_norm(grads, clip_norm=1.0)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/ops/clip_ops.py", line 259, in clip_by_global_norm
    "Found Inf or NaN global norm.")
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/ops/numerics.py", line 45, in verify_tensor_all_finite
    verify_input = array_ops.check_numerics(t, message=msg)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 817, in check_numerics
    "CheckNumerics", tensor=tensor, message=message, name=name)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Found Inf or NaN global norm. : Tensor had NaN values
	 [[{{node VerifyFinite/CheckNumerics}} = CheckNumerics[T=DT_FLOAT, message="Found Inf or NaN global norm.", _device="/job:localhost/replica:0/task:0/device:GPU:0"](global_norm/global_norm)]]

INFO:tensorflow:training_loop marked as finished
WARNING:tensorflow:Reraising captured error
Traceback (most recent call last):
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Found Inf or NaN global norm. : Tensor had NaN values
	 [[{{node VerifyFinite/CheckNumerics}} = CheckNumerics[T=DT_FLOAT, message="Found Inf or NaN global norm.", _device="/job:localhost/replica:0/task:0/device:GPU:0"](global_norm/global_norm)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_classifier.py", line 910, in <module>
    tf.app.run()
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_classifier.py", line 836, in main
    estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2400, in train
    rendezvous.raise_errors()
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/error_handling.py", line 128, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home///.local/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2394, in train
    saving_listeners=saving_listeners
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 356, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1181, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1215, in _train_model_default
    saving_listeners)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1409, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1148, in run
    run_metadata=run_metadata)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1239, in run
    raise six.reraise(*original_exc_info)
  File "/home///.local/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1224, in run
    return self._sess.run(*args, **kwargs)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1296, in run
    run_metadata=run_metadata)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Found Inf or NaN global norm. : Tensor had NaN values
	 [[{{node VerifyFinite/CheckNumerics}} = CheckNumerics[T=DT_FLOAT, message="Found Inf or NaN global norm.", _device="/job:localhost/replica:0/task:0/device:GPU:0"](global_norm/global_norm)]]

Caused by op 'VerifyFinite/CheckNumerics', defined at:
  File "run_classifier.py", line 910, in <module>
    tf.app.run()
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_classifier.py", line 836, in main
    estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2394, in train
    saving_listeners=saving_listeners
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 356, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1181, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1211, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2186, in _call_model_fn
    features, labels, mode, config)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1169, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2470, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1250, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1524, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "run_classifier.py", line 636, in model_fn
    total_loss, learning_rate, num_train_steps, num_warmup_steps, use_tpu)
  File "/home///zklcode/pynlp/bert/bert/optimization.py", line 74, in create_optimizer
    (grads, _) = tf.clip_by_global_norm(grads, clip_norm=1.0)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/ops/clip_ops.py", line 259, in clip_by_global_norm
    "Found Inf or NaN global norm.")
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/ops/numerics.py", line 45, in verify_tensor_all_finite
    verify_input = array_ops.check_numerics(t, message=msg)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 817, in check_numerics
    "CheckNumerics", tensor=tensor, message=message, name=name)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/home///anaconda3/envs/tfzkl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Found Inf or NaN global norm. : Tensor had NaN values
	 [[{{node VerifyFinite/CheckNumerics}} = CheckNumerics[T=DT_FLOAT, message="Found Inf or NaN global norm.", _device="/job:localhost/replica:0/task:0/device:GPU:0"](global_norm/global_norm)]]

**Comment by zkl99999** [comment]
python run_classifier.py \
  --task_name=MRPC \
  --do_train=true \
  --do_eval=true \
  --data_dir=$GLUE_DIR/MRPC \
  --vocab_file=$BERT_BASE_DIR/vocab.txt \
  --bert_config_file=$BERT_BASE_DIR/bert_config.json \
  --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt \
  --max_seq_length=128 \
  --train_batch_size=32 \
  --learning_rate=2e-5 \
  --num_train_epochs=3.0 \
  --output_dir=/tmp/mrpc_output/

**Comment by zkl99999** [comment]
reduce the batch_size ,it is ok
set parameter   --max_seq_length=256  --train_batch_size=16,

**Comment by anpark** [comment]
same problem.

**Comment by freefuiiismyname** [comment]
hi，bro.
i meet the same problem,and i dont understand why reducing batch_size make it work.(this really work)
do u have any ideas?

**Comment by daishu7** [comment]
hello，I add POS tag feature to the  BERT model and meet the same problem，I tried to reduce the batch_size, but it was useless.

python run_oqmrc_POS.py --task_name=MyPro --do_train=true --do_eval=true --data_dir=./data --vocab_file=chinese_bert/vocab.txt --pos_tag_vocab_file=pyltp_data/pos_tag_vocab.txt --bert_config_file=chinese_bert/bert_config.json --max_seq_length=128 --train_batch_size=32 --learning_rate=2e-5 --num_train_epochs=3.0 --output_dir=tmp/mypro_output_POS/
![image](https://user-images.githubusercontent.com/22828828/61690225-6afb6400-ad5b-11e9-8056-8f71f78556a8.png)
![image](https://user-images.githubusercontent.com/22828828/61690447-e8bf6f80-ad5b-11e9-9dd5-4177f85cbe5a.png)

**Comment by raj5287** [comment]
@daishu7 how did you create vocab.txt for chinese?
