### ISSUE TITLE
Pretraining - ValueError

### ISSUE THREAD

**Issue by marwage** [google-research/bert#936]
Hello BERT community!

I would like to run the pretraining but I am stuck with an error.

My procedure is the following.
1. download the Wikipedia dump
2. use the wikiextractor
3. use Spacy to get files with a sentence for each line
```
import spacy
import re
import os


def segment_dir(nlp, dir):
    for file in os.scandir(dir):
        if file.is_file() and file.name != ".DS_Store":
            print("file " + str(file.name))
            with open(file, "r") as text_file:
                text = text_file.read()

            text = re.sub(r"[\n]{2,}", "\n", text)
            text = re.sub(r"<.*>\n", "", text)
            text = re.sub(r"^[^\s]+\n", "", text)

            doc = nlp(text, disable=["tagger", "ner"])
            with open(dir.path + "/sample_text.txt", "a") as out_file:
                for sent in doc.sents:
                    out_file.write(re.sub(r"\n", "", str(sent)) + "\n")


def main():
    nlp = spacy.load("en_core_web_lg")
    nlp.max_length = 1500000

    for dir in os.scandir():
        if dir.is_dir():
            print("dir " + str(dir.name))
            segment_dir(nlp, dir)


if __name__ == "__main__":
    main()
```
4. create tf_record for each sample_text using `create_pretraining_data.py`
5. run `run_pretraining.py`

Then I get the following error
```
[[1;32m169.254.128.185.10000[m::stderr] INFO:tensorflow:*** Input Files ***
[[1;32m169.254.128.185.10000[m::stderr] WARNING:tensorflow:Estimator's model_fn (<function model_fn_builder.<locals>.model_fn at 0x7f22940faae8>) includes params argument, but params are not passed to Estimator.
[[1;32m169.254.128.185.10000[m::stderr] INFO:tensorflow:Using config: {'_model_dir': '/cache/out_dir', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': 1000, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
[[1;32m169.254.128.185.10000[m::stderr] graph_options {
[[1;32m169.254.128.185.10000[m::stderr]   rewrite_options {
[[1;32m169.254.128.185.10000[m::stderr]     meta_optimizer_iterations: ONE
[[1;32m169.254.128.185.10000[m::stderr]   }
[[1;32m169.254.128.185.10000[m::stderr] }
[[1;32m169.254.128.185.10000[m::stderr] , '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': None, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f2192c78160>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_tpu_config': TPUConfig(iterations_per_loop=1000, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None), '_cluster': None}
[[1;32m169.254.128.185.10000[m::stderr] INFO:tensorflow:_TPUContext: eval_on_tpu True
[[1;32m169.254.128.185.10000[m::stderr] WARNING:tensorflow:eval_on_tpu ignored because use_tpu is False.
[[1;32m169.254.128.185.10000[m::stderr] INFO:tensorflow:***** Running training *****
[[1;32m169.254.128.185.10000[m::stderr] INFO:tensorflow:  Batch size = 32
[[1;32m169.254.128.185.10000[m::stderr] WARNING:tensorflow:From /home/work/user-job-dir/src/bert_kf/run_pretraining.py:368: parallel_interleave (from tensorflow.contrib.data.python.ops.interleave_ops) is deprecated and will be removed in a future version.
[[1;32m169.254.128.185.10000[m::stderr] Instructions for updating:
[[1;32m169.254.128.185.10000[m::stderr] Use `tf.data.experimental.parallel_interleave(...)`.
[[1;32m169.254.128.185.10000[m::stderr] INFO:tensorflow:Error recorded from training_loop: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32, device=/device:CPU:0)'
[[1;32m169.254.128.185.10000[m::stderr] INFO:tensorflow:training_loop marked as finished
[[1;32m169.254.128.185.10000[m::stderr] WARNING:tensorflow:Reraising captured error
[[1;32m169.254.128.185.10000[m::stderr] Traceback (most recent call last):
[[1;32m169.254.128.185.10000[m::stderr]   File "/home/work/user-job-dir/src/bert_kf/run_pretraining.py", line 493, in <module>
[[1;32m169.254.128.185.10000[m::stderr]     tf.app.run()
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
[[1;32m169.254.128.185.10000[m::stderr]     _sys.exit(main(argv))
[[1;32m169.254.128.185.10000[m::stderr]   File "/home/work/user-job-dir/src/bert_kf/run_pretraining.py", line 466, in main
[[1;32m169.254.128.185.10000[m::stderr]     estimator.train(input_fn=train_input_fn, max_steps=FLAGS.num_train_steps)
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2409, in train
[[1;32m169.254.128.185.10000[m::stderr]     rendezvous.raise_errors()
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/error_handling.py", line 128, in raise_errors
[[1;32m169.254.128.185.10000[m::stderr]     six.reraise(typ, value, traceback)
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
[[1;32m169.254.128.185.10000[m::stderr]     raise value
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2403, in train
[[1;32m169.254.128.185.10000[m::stderr]     saving_listeners=saving_listeners
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
[[1;32m169.254.128.185.10000[m::stderr]     loss = self._train_model(input_fn, hooks, saving_listeners)
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
[[1;32m169.254.128.185.10000[m::stderr]     return self._train_model_default(input_fn, hooks, saving_listeners)
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1234, in _train_model_default
[[1;32m169.254.128.185.10000[m::stderr]     input_fn, model_fn_lib.ModeKeys.TRAIN))
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1075, in _get_features_and_labels_from_input_fn
[[1;32m169.254.128.185.10000[m::stderr]     self._call_input_fn(input_fn, mode))
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2363, in _call_input_fn
[[1;32m169.254.128.185.10000[m::stderr]     return input_fn(**kwargs)
[[1;32m169.254.128.185.10000[m::stderr]   File "/home/work/user-job-dir/src/bert_kf/run_pretraining.py", line 368, in input_fn
[[1;32m169.254.128.185.10000[m::stderr]     cycle_length=cycle_length))
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1190, in apply
[[1;32m169.254.128.185.10000[m::stderr]     dataset = transformation_func(self)
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/data/experimental/ops/interleave_ops.py", line 87, in _apply_fn
[[1;32m169.254.128.185.10000[m::stderr]     buffer_output_elements, prefetch_input_elements)
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/readers.py", line 134, in __init__
[[1;32m169.254.128.185.10000[m::stderr]     cycle_length, block_length)
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2714, in __init__
[[1;32m169.254.128.185.10000[m::stderr]     super(InterleaveDataset, self).__init__(input_dataset, map_func)
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2677, in __init__
[[1;32m169.254.128.185.10000[m::stderr]     experimental_nested_dataset_support=True)
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1860, in __init__
[[1;32m169.254.128.185.10000[m::stderr]     self._function.add_to_graph(ops.get_default_graph())
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 479, in add_to_graph
[[1;32m169.254.128.185.10000[m::stderr]     self._create_definition_if_needed()
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 335, in _create_definition_if_needed
[[1;32m169.254.128.185.10000[m::stderr]     self._create_definition_if_needed_impl()
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 344, in _create_definition_if_needed_impl
[[1;32m169.254.128.185.10000[m::stderr]     self._capture_by_value, self._caller_device)
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 864, in func_graph_from_py_func
[[1;32m169.254.128.185.10000[m::stderr]     outputs = func(*func_graph.inputs)
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1794, in tf_data_structured_function_wrapper
[[1;32m169.254.128.185.10000[m::stderr]     ret = func(*nested_args)
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/readers.py", line 200, in __init__
[[1;32m169.254.128.185.10000[m::stderr]     filenames = ops.convert_to_tensor(filenames, dtype=dtypes.string)
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1050, in convert_to_tensor
[[1;32m169.254.128.185.10000[m::stderr]     as_ref=False)
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
[[1;32m169.254.128.185.10000[m::stderr]     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
[[1;32m169.254.128.185.10000[m::stderr]   File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 983, in _TensorTensorConversionFunction
[[1;32m169.254.128.185.10000[m::stderr]     (dtype.name, t.dtype.name, str(t)))
[[1;32m169.254.128.185.10000[m::stderr] ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32, device=/device:CPU:0)'
```

Can someone tell me what the issue is?
Thank you!

**Comment by GanjinZero** [comment]
I have the same issue with you, can you tell me how do you solve the problem(or not)?

**Comment by fajri91** [comment]
Same issue. Anyone?

**Comment by fajri91** [comment]
> I have the same issue with you, can you tell me how do you solve the problem(or not)?

Just make sure your path is correct for your input

**Comment by danyaljj** [comment]
Same issue here.
