### ISSUE TITLE
Error while using bert as tfhub layer with tensorflow 2.0

### ISSUE THREAD

**Issue by SilverLiningSL** [google-research/bert#938]
I'm trying to use bert as a keras layer in tensorflow 2.0 by tfhub. An issue came up that I can use model.predict alone,  but once I add the line 'model.compile()', I cannot even predict but get error down below, which makes it impossible for me to fit and use the model.

code is like:
```python
import tensorflow_hub as hub
import tensorflow as tf
from bert.tokenization import FullTokenizer
# from tensorflow.keras.models import Model
from tensorflow.keras import Model
from tensorflow.keras.callbacks import ModelCheckpoint
import tensorflow.keras as keras
from sklearn.metrics import f1_score,precision_score,recall_score

import numpy as np
import os


max_seq_length = 128  # Your choice here.
input_word_ids = tf.keras.layers.Input(shape=(max_seq_length,), dtype=tf.int32,
                                       name="input_word_ids")
input_mask = tf.keras.layers.Input(shape=(max_seq_length,), dtype=tf.int32,
                                   name="input_mask")
segment_ids = tf.keras.layers.Input(shape=(max_seq_length,), dtype=tf.int32,
                                    name="segment_ids")
bert_layer = hub.KerasLayer("english2",
                            trainable=True)
pooled_output, sequence_output = bert_layer([input_word_ids, input_mask, segment_ids])

out = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(128))(sequence_output)

model = Model(inputs=[input_word_ids, input_mask, segment_ids], outputs=out)
adam = tf.keras.optimizers.Adam(learning_rate=0.01)
model.compile(optimizer=adam ,loss='mse')
model.summary()

def get_masks(tokens, max_seq_length):
    """Mask for padding"""
    if len(tokens)>max_seq_length:
        raise IndexError("Token length more than max seq length!")
    return [1]*len(tokens) + [0] * (max_seq_length - len(tokens))


def get_segments(tokens, max_seq_length):
    """Segments: 0 for the first sequence, 1 for the second"""
    if len(tokens)>max_seq_length:
        raise IndexError("Token length more than max seq length!")
    segments = []
    current_segment_id = 0
    for token in tokens:
        segments.append(current_segment_id)
        if token == "[SEP]":
            current_segment_id = 1
    return segments + [0] * (max_seq_length - len(tokens))


def get_ids(tokens, tokenizer, max_seq_length):
    """Token ids from Tokenizer vocab"""
    token_ids = tokenizer.convert_tokens_to_ids(tokens)
    input_ids = token_ids + [0] * (max_seq_length-len(token_ids))
    return input_ids
    
vocab_file = bert_layer.resolved_object.vocab_file.asset_path.numpy()
do_lower_case = bert_layer.resolved_object.do_lower_case.numpy()
tokenizer = FullTokenizer(vocab_file, do_lower_case)

s = "This is a nice sentence."
stokens = tokenizer.tokenize(s)
stokens = ["[CLS]"] + stokens + ["[SEP]"]

input_ids = np.array(get_ids(stokens, tokenizer, max_seq_length))
input_masks = np.array(get_masks(stokens, max_seq_length))
input_segments = np.array(get_segments(stokens, max_seq_length))

out = model.predict([[input_ids],[input_masks],[input_segments]])
print(out)
```

error:
```python
Traceback (most recent call last):
  File "tfhubtest.py", line 74, in <module>
    out = model.predict([[input_ids],[input_masks],[input_segments]])
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 909, in predict
    use_multiprocessing=use_multiprocessing)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 462, in predict
    steps=steps, callbacks=callbacks, **kwargs)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 444, in _model_iteration
    total_epochs=1)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 503, in _call
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 408, in _initialize
    *args, **kwds))
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1848, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 358, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 73, in distributed_function
    per_replica_function, args=(model, x, y, sample_weights))
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 760, in experimental_run_v2
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1787, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 2132, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper
    return func(*args, **kwargs)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 162, in _predict_on_batch
    return predict_on_batch(model, x)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 370, in predict_on_batch
    return model(inputs)  # pylint: disable=not-callable
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 847, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 708, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 860, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 847, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper
    return func(*args, **kwargs)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_hub/keras_layer.py", line 218, in call
    lambda: f(training=False))
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/framework/smart_cond.py", line 56, in smart_cond
    return false_fn()
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_hub/keras_layer.py", line 218, in <lambda>
    lambda: f(training=False))
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/saved_model/load.py", line 436, in _call_attribute
    return instance.__call__(*args, **kwargs)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 494, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1822, in __call__
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 358, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/saved_model/function_deserialization.py", line 262, in restored_function_body
    "\n\n".join(signature_descriptions)))
ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (3 total):
    * [<tf.Tensor 'inputs:0' shape=(None, 128) dtype=int64>, <tf.Tensor 'inputs_1:0' shape=(None, 128) dtype=int64>, <tf.Tensor 'inputs_2:0' shape=(None, 128) dtype=int64>]
    * False
    * None
  Keyword arguments: {}

Expected these arguments to match one of the following 4 option(s):

Option 1:
  Positional arguments (3 total):
    * [TensorSpec(shape=(None, None), dtype=tf.int32, name='input_word_ids'), TensorSpec(shape=(None, None), dtype=tf.int32, name='input_mask'), TensorSpec(shape=(None, None), dtype=tf.int32, name='input_type_ids')]
    * True
    * None
  Keyword arguments: {}

Option 2:
  Positional arguments (3 total):
    * [TensorSpec(shape=(None, None), dtype=tf.int32, name='input_word_ids'), TensorSpec(shape=(None, None), dtype=tf.int32, name='input_mask'), TensorSpec(shape=(None, None), dtype=tf.int32, name='input_type_ids')]
    * False
    * None
  Keyword arguments: {}

Option 3:
  Positional arguments (3 total):
    * [TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/0'), TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/1'), TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/2')]
    * True
    * None
  Keyword arguments: {}

Option 4:
  Positional arguments (3 total):
    * [TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/0'), TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/1'), TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/2')]
    * False
    * None
  Keyword arguments: {}

```

I'd appreciate if anyone have a solution for this.

**Comment by nikky78** [comment]
Hi ! Same problem for me, anyone could look into it please?

**Comment by AntoninaGerasiova** [comment]
Very similar problem. Will appreciate any help.

**Comment by AntoninaGerasiova** [comment]
Very similar problem. 
I tried to do this with my input data: 
`train_ids_tensor = tf.convert_to_tensor(
        train_ids[0:16], dtype=tf.int32, name='input_word_ids')

train_masks_tensor = tf.convert_to_tensor(
        train_masks[0:16], dtype=tf.int32, name='input_mask')

train_segments_tensor = tf.convert_to_tensor(
        train_segments[0:16], dtype=tf.int32, name='input_type_ids')`
And got new error:
`
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weights, batch_size, epochs, steps, shuffle, **kwargs)
    243             label, ", ".join([str(i.shape[0]) for i in nest.flatten(data)]))
    244       msg += "Please provide data which shares the same first dimension."
--> 245       raise ValueError(msg)
    246     num_samples = num_samples.pop()
    247 

ValueError: Data cardinality is ambiguous:
  x sizes: 10, 16, 25000
Please provide data which shares the same first dimension.`
So for whatever reason it tries flatten and concatenate input data. Totally  perplexed with this.
Will appreciate any help.

**Comment by ccuulinay** [comment]
Same here. 
tf version : 2.0.0
tf-hub version: 0.7.0

The "predict" will raise error after "compile" and "fit".

**Comment by jvitorc17** [comment]
Exactly the same problem.

**Comment by jvitorc17** [comment]
Hi @SilverLiningSL 
Intead of
`out = model.predict([[input_ids],[input_masks],[input_segments]])`
try
`out = model.predict([tf.constant([input_ids], dtype='int32'), tf.constant([input_masks], dtype='int32'), tf.constant([input_segments], dtype='int32')])`
I hope this helps!!!

**Comment by KacperKubara** [comment]
Hi ,
I've got very similar error to that:
``` Python
    ValueError: Could not find matching function to call loaded from the SavedModel. Got:
      Positional arguments (3 total):
        * [<tf.Tensor 'inputs:0' shape=() dtype=int32>, <tf.Tensor 'inputs_1:0' shape=() dtype=int32>, <tf.Tensor 'inputs_2:0' shape=() dtype=int32>]
        * True
        * None
      Keyword arguments: {}

    Expected these arguments to match one of the following 4 option(s):

    Option 1:
      Positional arguments (3 total):
        * [TensorSpec(shape=(None, None), dtype=tf.int32, name='input_word_ids'), TensorSpec(shape=(None, None), dtype=tf.int32, name='input_mask'), TensorSpec(shape=(None, None), dtype=tf.int32, name='input_type_ids')]
        * True
        * None
      Keyword arguments: {}

    Option 2:
      Positional arguments (3 total):
        * [TensorSpec(shape=(None, None), dtype=tf.int32, name='input_word_ids'), TensorSpec(shape=(None, None), dtype=tf.int32, name='input_mask'), TensorSpec(shape=(None, None), dtype=tf.int32, name='input_type_ids')]
        * False
        * None
      Keyword arguments: {}

    Option 3:
      Positional arguments (3 total):
        * [TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/0'), TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/1'), TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/2')]
        * True
        * None
      Keyword arguments: {}

    Option 4:
      Positional arguments (3 total):
        * [TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/0'), TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/1'), TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/2')]
        * False
        * None
      Keyword arguments: {}
```
After following @jvitorc17  advice I got the following error instead:
``` Python
TypeError: Expected int32, got <tf.Tensor 'ssc_model/strided_slice_1:0' shape=() dtype=int32> of type 'Tensor' instead.

```

Does anyone know how to solve it?

**Comment by sandeepthetechie** [comment]
> I'm trying to use bert as a keras layer in tensorflow 2.0 by tfhub. An issue came up that I can use model.predict alone, but once I add the line 'model.compile()', I cannot even predict but get error down below, which makes it impossible for me to fit and use the model.
> 
> code is like:
> 
> ```python
> import tensorflow_hub as hub
> import tensorflow as tf
> from bert.tokenization import FullTokenizer
> # from tensorflow.keras.models import Model
> from tensorflow.keras import Model
> from tensorflow.keras.callbacks import ModelCheckpoint
> import tensorflow.keras as keras
> from sklearn.metrics import f1_score,precision_score,recall_score
> 
> import numpy as np
> import os
> 
> 
> max_seq_length = 128  # Your choice here.
> input_word_ids = tf.keras.layers.Input(shape=(max_seq_length,), dtype=tf.int32,
>                                        name="input_word_ids")
> input_mask = tf.keras.layers.Input(shape=(max_seq_length,), dtype=tf.int32,
>                                    name="input_mask")
> segment_ids = tf.keras.layers.Input(shape=(max_seq_length,), dtype=tf.int32,
>                                     name="segment_ids")
> bert_layer = hub.KerasLayer("english2",
>                             trainable=True)
> pooled_output, sequence_output = bert_layer([input_word_ids, input_mask, segment_ids])
> 
> out = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(128))(sequence_output)
> 
> model = Model(inputs=[input_word_ids, input_mask, segment_ids], outputs=out)
> adam = tf.keras.optimizers.Adam(learning_rate=0.01)
> model.compile(optimizer=adam ,loss='mse')
> model.summary()
> 
> def get_masks(tokens, max_seq_length):
>     """Mask for padding"""
>     if len(tokens)>max_seq_length:
>         raise IndexError("Token length more than max seq length!")
>     return [1]*len(tokens) + [0] * (max_seq_length - len(tokens))
> 
> 
> def get_segments(tokens, max_seq_length):
>     """Segments: 0 for the first sequence, 1 for the second"""
>     if len(tokens)>max_seq_length:
>         raise IndexError("Token length more than max seq length!")
>     segments = []
>     current_segment_id = 0
>     for token in tokens:
>         segments.append(current_segment_id)
>         if token == "[SEP]":
>             current_segment_id = 1
>     return segments + [0] * (max_seq_length - len(tokens))
> 
> 
> def get_ids(tokens, tokenizer, max_seq_length):
>     """Token ids from Tokenizer vocab"""
>     token_ids = tokenizer.convert_tokens_to_ids(tokens)
>     input_ids = token_ids + [0] * (max_seq_length-len(token_ids))
>     return input_ids
>     
> vocab_file = bert_layer.resolved_object.vocab_file.asset_path.numpy()
> do_lower_case = bert_layer.resolved_object.do_lower_case.numpy()
> tokenizer = FullTokenizer(vocab_file, do_lower_case)
> 
> s = "This is a nice sentence."
> stokens = tokenizer.tokenize(s)
> stokens = ["[CLS]"] + stokens + ["[SEP]"]
> 
> input_ids = np.array(get_ids(stokens, tokenizer, max_seq_length))
> input_masks = np.array(get_masks(stokens, max_seq_length))
> input_segments = np.array(get_segments(stokens, max_seq_length))
> 
> out = model.predict([[input_ids],[input_masks],[input_segments]])
> print(out)
> ```
> 
> error:
> 
> ```python
> Traceback (most recent call last):
>   File "tfhubtest.py", line 74, in <module>
>     out = model.predict([[input_ids],[input_masks],[input_segments]])
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 909, in predict
>     use_multiprocessing=use_multiprocessing)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 462, in predict
>     steps=steps, callbacks=callbacks, **kwargs)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 444, in _model_iteration
>     total_epochs=1)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 123, in run_one_epoch
>     batch_outs = execution_function(iterator)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
>     distributed_function(input_fn))
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
>     result = self._call(*args, **kwds)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 503, in _call
>     self._initialize(args, kwds, add_initializers_to=initializer_map)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 408, in _initialize
>     *args, **kwds))
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1848, in _get_concrete_function_internal_garbage_collected
>     graph_function, _, _ = self._maybe_define_function(args, kwargs)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2150, in _maybe_define_function
>     graph_function = self._create_graph_function(args, kwargs)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2041, in _create_graph_function
>     capture_by_value=self._capture_by_value),
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
>     func_outputs = python_func(*func_args, **func_kwargs)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 358, in wrapped_fn
>     return weak_wrapped_fn().__wrapped__(*args, **kwds)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 73, in distributed_function
>     per_replica_function, args=(model, x, y, sample_weights))
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 760, in experimental_run_v2
>     return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1787, in call_for_each_replica
>     return self._call_for_each_replica(fn, args, kwargs)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 2132, in _call_for_each_replica
>     return fn(*args, **kwargs)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper
>     return func(*args, **kwargs)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 162, in _predict_on_batch
>     return predict_on_batch(model, x)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 370, in predict_on_batch
>     return model(inputs)  # pylint: disable=not-callable
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 847, in __call__
>     outputs = call_fn(cast_inputs, *args, **kwargs)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 708, in call
>     convert_kwargs_to_constants=base_layer_utils.call_context().saving)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 860, in _run_internal_graph
>     output_tensors = layer(computed_tensors, **kwargs)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 847, in __call__
>     outputs = call_fn(cast_inputs, *args, **kwargs)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper
>     return func(*args, **kwargs)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_hub/keras_layer.py", line 218, in call
>     lambda: f(training=False))
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/framework/smart_cond.py", line 56, in smart_cond
>     return false_fn()
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_hub/keras_layer.py", line 218, in <lambda>
>     lambda: f(training=False))
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/saved_model/load.py", line 436, in _call_attribute
>     return instance.__call__(*args, **kwargs)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
>     result = self._call(*args, **kwds)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 494, in _call
>     results = self._stateful_fn(*args, **kwds)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1822, in __call__
>     graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2150, in _maybe_define_function
>     graph_function = self._create_graph_function(args, kwargs)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2041, in _create_graph_function
>     capture_by_value=self._capture_by_value),
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
>     func_outputs = python_func(*func_args, **func_kwargs)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 358, in wrapped_fn
>     return weak_wrapped_fn().__wrapped__(*args, **kwds)
>   File "/home/mhan/slining/lib/python3.6/site-packages/tensorflow_core/python/saved_model/function_deserialization.py", line 262, in restored_function_body
>     "\n\n".join(signature_descriptions)))
> ValueError: Could not find matching function to call loaded from the SavedModel. Got:
>   Positional arguments (3 total):
>     * [<tf.Tensor 'inputs:0' shape=(None, 128) dtype=int64>, <tf.Tensor 'inputs_1:0' shape=(None, 128) dtype=int64>, <tf.Tensor 'inputs_2:0' shape=(None, 128) dtype=int64>]
>     * False
>     * None
>   Keyword arguments: {}
> 
> Expected these arguments to match one of the following 4 option(s):
> 
> Option 1:
>   Positional arguments (3 total):
>     * [TensorSpec(shape=(None, None), dtype=tf.int32, name='input_word_ids'), TensorSpec(shape=(None, None), dtype=tf.int32, name='input_mask'), TensorSpec(shape=(None, None), dtype=tf.int32, name='input_type_ids')]
>     * True
>     * None
>   Keyword arguments: {}
> 
> Option 2:
>   Positional arguments (3 total):
>     * [TensorSpec(shape=(None, None), dtype=tf.int32, name='input_word_ids'), TensorSpec(shape=(None, None), dtype=tf.int32, name='input_mask'), TensorSpec(shape=(None, None), dtype=tf.int32, name='input_type_ids')]
>     * False
>     * None
>   Keyword arguments: {}
> 
> Option 3:
>   Positional arguments (3 total):
>     * [TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/0'), TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/1'), TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/2')]
>     * True
>     * None
>   Keyword arguments: {}
> 
> Option 4:
>   Positional arguments (3 total):
>     * [TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/0'), TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/1'), TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/2')]
>     * False
>     * None
>   Keyword arguments: {}
> ```
> 
> I'd appreciate it if anyone have a solution for this.

try to return tuple in your get_ids function. I hope that helps.


def get_ids(tokens, tokenizer, max_seq_length):
    """Token ids from Tokenizer vocab"""
    token_ids = tokenizer.convert_tokens_to_ids(tokens)
    input_ids = token_ids + [0] * (max_seq_length-len(token_ids))
    return tuple(input_ids)
